### ISSUE TITLE
Can not build on illumos

### ISSUE THREAD

**Issue by Toasterson** [sagiegurari/fsio#10]
### Describe The Bug
The users crate has a open PR which is required to build on illumos

### To Reproduce
Build this crate on illumos

### Link to PR
ogham/rust-users#49

**Comment by sagiegurari** [comment]
i see the PR is open for a long time with no response. any better alternative to that crate?

**Comment by Toasterson** [comment]
In your usecase maybe libc crate directly? the users crate is pretty fundamental and seems unmaintained. A request for maintainer change is the only thing I can come up with. crates like whoami use the posix and windows API's directly but also lack illumos support. And the API you are using is pretty much one libc function that could be copied from the users crate.

If I look at https://github.com/ogham/rust-users/blob/master/src/base.rs#L552-L557 one could rip out these two functions and thats all that this crate needs. The incompatible parts are the Os specific extensions that the users crate also supports.

**Comment by sagiegurari** [comment]
i'm thinking i can make it even simpler.... let me investigate it a bit.

**Comment by sagiegurari** [comment]
@Toasterson i think it should be resolved now.

**Comment by Toasterson** [comment]
Yeah that definitely resolves the issue. And I think in the context of cargo-make this also adds a nice prefix to the path that should also work on Windows?

**Comment by sagiegurari** [comment]
for windows the scripts are positioned in <temp dir>/fsio/randomfile while in linux/mac/... its at <temp dir>/fsio_<random>/fsio/randomfile
reason is that the temp dir can be shared in linux so i need an upper level folder to be different between users so it can be deleted later on. before, i used the username but now i'm just putting some random string.

**Comment by sagiegurari** [comment]
closing as this is resolved.
